### ISSUE TITLE
Pitch: Scale up/down a cluster!

### ISSUE THREAD

**Issue by marregui** [crate/crate-howtos#180] opened 2020-06-15 18:16 UTC
# Pitch

Scale up/down a cluster!

- Best Practice  
- Needed changes in configuration
- Consequences/tradeoffs/pitfalls 

This request comes from a discussion.

# Launch checklist

Follow the launch checklist to get new content ideas from pitch to published. Use the comments on this issue to provide the information requested.

- [ ] Provide context

   - Who is the audience for this content?

   - What problem should this content solve for the reader?

   - What is the best format for this content (e.g, blog post, docs tutorial, etc.)?

   - Why is this content important for the company?

   - How urgent is this content?

- [ ] Identify an author

   The ideal content author knows the most about what has to be written about. Typically, this is a domain expert or someone with relevant hands-on experience.

   The @crate/tech-writing team can help locate an author.

   Alternatively, a @crate/tech-writing team member can author the content. Note, however, this may slow things down if the technical writer has to learn the topic before writing about it.

- [ ] Create an outline

   You have a description of the content idea. Before writing starts, the description should be turned into an *outline*.

   You can think of an outline as a set of bullet-point notes that summarizes the content structure. A good outline is the starting point for a draft.

- [ ] Produce a first draft

   The author should produce a first draft, using the outline as a guide.

Once the author has produced the first draft, editing can begin. If the author is not a technical writer, a member of the @crate/tech-writing team will provide editorial support and help the author bring the piece to fruition.

**Comment by mechanomi** [comment] 2020-06-16 07:57
thanks for reporting this request, @marregui! someone from the @crate/docs team will let you know when we have updates

**Comment by mechanomi** [comment] 2020-06-16 09:12
see also: https://github.com/crate/crate-howtos/issues/175

**Comment by mechanomi** [comment] 2020-07-27 07:51
@marregui we changed the way @crate/tech-writing use GitHub labels. accordingly, I have re-triaged this issue

*NOTE: I have edited the issue description to match the issue template for [new content pitches](https://github.com/crate/tech-writing-domain/issues/new/choose)*

please review the *launch checklist* (above) and let me (or any @crate/tech-writing team member) know if you want help or have any questions

**Comment by mechanomi** [comment] 2020-07-27 08:02
see https://github.com/crate/tech-writing-domain/issues/10

**Comment by mechanomi** [comment] 2020-07-27 08:04
closing as a duplicate of https://github.com/crate/tech-writing-domain/issues/10

**Closed by mechanomi** 2020-07-27 08:04 UTC
Labels: duplicate, team: tech writing
